version: '3.5'

services:

  frontend:
    image: frontend
    ports: 
      - 5000:5000
    command: serve -s -l 5000 build
    container_name: frontend-container

  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    command: ./server
    container_name: backend-container
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis-container

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db-container

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    container_name: nginx-container
