version: '3.5'

services:

  frontend:
    image: frontend
    ports: 
      - 5000:5000
    command: serve -s -l 5000 build
    container_name: frontend-container

  backend:
    image: backend
    ports:
      - 8080:8080
    command: ./server
    container_name: backend-container